### PR TITLE
co-exist with existing step definitions

### PR DESCRIPTION
**Pull request by Adezandee**
Hey guys,

You've done a great job on automated testing, it's pretty cool!  
After read your document, I found you override World.Given / World.When / World.Then, and your version expect different function signature. I think this would be a obstacle for those who want to use cucumber-mink in the halfway.

What do you think? Should cucumber-mink provide it's own Given / When / Then?

### CODE REVIEW

**Comment by Adezandee** [comment]
Hi, @cades
Here is my proposal to answer the issue, i pretty much followed your recommendation because it feels right to me. What do you think ? I'll release a new package version after this

**Comment by cades** [comment]
Hi, @Adezandee 
I really appreciate your time and effort, I saw your code and I think we are almost there!

The current implement [automatically attach](https://github.com/Adezandee/cucumber-mink/pull/12/files#diff-5f324350b40b0a16562d7f7acfd70837R50) `mink` to cucumber world object. Since node.js module is a singleton object, user can access it through `require`, this is the reason why I think we should leave cucumber world object un-touched. Let me use example in README.md:

```js
var mink = require('cucumber-mink');

module.exports = function () {
  mink.call(this);
  this.mink = mink;  // user can attach mink to world if she want
};
```

```js
// features/step_definitions/login.js

var Mink = require('cucumber-mink'),
    Ext  = Mink.Ext;

/////////////////////////

function login (Driver, callback) {
  var stepsArray = [...];
  return Mink.metaStep(Driver, stepsArray, callback);
}

/////////////////////////

module.exports = function() {
  Mink.defineStep(/^I am logged in$/, login);  // use the required one also works
};
```

**Comment by Adezandee** [comment]
@cades yup, good point :) should be fine now

**Comment by cades** [comment]
Great! I think it's time to merge this PR

**Comment by Adezandee** [comment]
Done, released v0.4.0

**Pull request merged**
